---
- name: Manage docker container
  hosts: localhost
  become: yes
  tasks:
    - name: Install Docker Python Library
      pip:
        name: docker
        state: present
    - name: Pull Docker Image
      docker_image:
        name: nginx:latest
    - name: Run Docker container
      docker_container:
        name: my_nginx_container
        image: nginx:latest
        ports:
          - "8080:80"
        state: started
